name: Vercel Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCAL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCAL_PROJECT_ID }}
 
on:
  push:
    branches:
      - main
 
jobs:
  Deploy-developent:
    runs-on: ubuntu-latest
 
    steps:
      - name: "checkout code"
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Install npm
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Enviroment Information
        run: vercel pull --yes --enviroment=development --token=${{ secrets.VERCAL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCAL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCAL_TOKEN }}

        
